openapi: 3.0.1
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório.
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Suporte Dev
    email: contato@examplo.com
    url: https://mockapi.io
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/license/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
  - url: https://6096015d116f3f00174b29ba.mockapi.io/
    description: API de testes
paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades
      responses:
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                        type: string
    post: 
      summary: Cria novas especialidades
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                      type: string
  /especialidades/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                      type: string
        404:
          description: Especiaidade não encontrada
          content:
            application/json:
              example: "Not Found"
    delete:
      summary: Deleta especialidade
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
      404:
        description: ID não encontrado
        content:
          application/json:
            example: "Not Found"
